name: Deploy to Lightsail

on:
  push:
    branches: [ "main" ]
    # Or specify whichever branch you want to trigger from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"  # or any version you need

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Deploy the build folder directly to Lightsail
      - name: Deploy to Lightsail via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: "build/*"
          target: "/home/bitnami/memory-bridge"
